### ISSUE TITLE
not the output in demo

### ISSUE THREAD

**Issue by Aishwaryabaskaran** [vijayvee/video-captioning#17]
Hello,
First of all, thanks for the repo. It's of great help.
I tried using it with the pretrained model ckpt provided. The outputs are gibberish and not any useful sentence. I am unable to figure out what the issue is. Please help.

**Comment by rupeshchandgude** [comment]
I am facing same problem. I have followed the sequence mentioned and trained the model. while training the results shown are relatable with GT. But while running test file, it always shows same sentence for every video and the sentence contains same words repeatably.
I have attached the error file which contains the training results and testing results.

[error.txt](https://github.com/vijayvee/video-captioning/files/3110943/error.txt)

**Comment by vijayvee** [comment]
Hi @rupeshchandgude, I think the error that you're mentioning is slightly different from what @Aishwaryabaskaran was facing since your predictions are not using the same model that I provided with the repo. Could you please check if your results make more sense when restoring from the checkpoint I provided?

From your output, it seems that your model is overfitting on the training set. Are you sure you are using regularization techniques correctly in the model?

**Comment by abhaygargab** [comment]
Was this problem solved?? I am using the model weights and checkpoint from the repository but my output is always same (repeated words without <EOS>) for any input.
Will be thankful for any hints on this.

**Comment by vijayvee** [comment]
Thanks for your interest in the repo, I don't think this is a wrong checkpoint file since I created my demo video with this file. How does the train set output look for you?

**Comment by abhaygargab** [comment]
I solved the issue by replacing the line in Extract_Feats.py-
frame = skimage.transform.resize(frame,[224,224]) with
frame = skimage.transform.resize(frame,[224,224], preserve_range=True).
I found this solution following this issue-
https://github.com/chenxinpeng/S2VT/issues/5

**Comment by vijayvee** [comment]
That's great, thanks for sharing @abhaygargab ! Closing this issue for now, please reopen if the above solution doesn't work for anyone.
